### PR TITLE
Fix applicationRootPath When Publishing well crash

### PR DESCRIPTION
**Pull request by xzeertacat**
Fix applicationRootPath When Publishing well crash

### CODE REVIEW

**Comment by hishamco** [comment]
Let me verify your changes .. thanks

**Comment by hishamco** [comment]
Sorry @xzeertacat for late .. I'm checking your PR, seems you break my commit https://github.com/hishamco/My.Extensions.Localization.Json/commit/2bc6ce14daa88c31bae517a73c406c9fcf5505dd that fixes issue #3

**Comment by hishamco** [comment]
I test the sample in both debug and release mode .. it works as expected, could you please create a minimal repo to reproduce your issue

**Comment by xzeertacat** [comment]
please put this dockerfile in project root
and build with linux container
```dockerifle
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY . .
WORKDIR "/src/samples/LocalizationSample"
RUN dotnet restore "LocalizationSample.csproj"
RUN dotnet build "LocalizationSample.csproj" -c Release -o /app

FROM build AS publish
WORKDIR "/src/samples/LocalizationSample"
RUN dotnet publish "LocalizationSample.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "LocalizationSample.dll"]
```
Run below command
1. `docker build -t test1 .`
2. `docker run -p 8080:80 test1`

then will crash , this is the logs
```
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
Application startup exception: System.Exception: Could not resolve a service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[[LocalizationSample.Startup, LocalizationSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' for the parameter 'localizer1' of method 'Configure' on type 'LocalizationSample.Startup'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at My.Extensions.Localization.Json.JsonStringLocalizerFactory.Create(Type resourceSource) in /src/src/My.Extensions.Localization.Json/JsonStringLocalizerFactory.cs:line 37
   at Microsoft.Extensions.Localization.StringLocalizer`1..ctor(IStringLocalizerFactory factory)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.Exception: Could not resolve a service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[[LocalizationSample.Startup, LocalizationSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' for the parameter 'localizer1' of method 'Configure' on type 'LocalizationSample.Startup'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at My.Extensions.Localization.Json.JsonStringLocalizerFactory.Create(Type resourceSource) in /src/src/My.Extensions.Localization.Json/JsonStringLocalizerFactory.cs:line 37
   at Microsoft.Extensions.Localization.StringLocalizer`1..ctor(IStringLocalizerFactory factory)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[5]
      Hosting shutdown

Unhandled Exception: System.Exception: Could not resolve a service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[[LocalizationSample.Startup, LocalizationSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' for the parameter 'localizer1' of method 'Configure' on type 'LocalizationSample.Startup'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at My.Extensions.Localization.Json.JsonStringLocalizerFactory.Create(Type resourceSource) in /src/src/My.Extensions.Localization.Json/JsonStringLocalizerFactory.cs:line 37
   at Microsoft.Extensions.Localization.StringLocalizer`1..ctor(IStringLocalizerFactory factory)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at LocalizationSample.Program.Main(String[] args) in /src/samples/LocalizationSample/Program.cs:line 12
```

**Comment by hishamco** [comment]
I didn't deal with docker before, but I will try to have a look, meanwhile you can try `http://localhost/?culture=fr-FR&ui-culture=fr-FR` with your changes, both localizers in the sample should display Bounjor

**Comment by xzeertacat** [comment]
In the previous version lose another project localization file , I have no idea to locate all probability
I try to list all possible path to find it
the priority is :  
1. original project folder
2. entry project folder
3. publish folder

**Comment by hishamco** [comment]
@xzeertacat I need to take this in consideration if we can reproduce it

@abarrak, and @Muhammad-Altabba can you reproduce this one?

**Comment by hishamco** [comment]
@xzeertacat I will close this because I simplify the application root in PR https://github.com/hishamco/My.Extensions.Localization.Json/pull/17

**Pull request closed without merging**
