### PR TITLE
Added functionality to support a 'root' fallback resource.

### PR DESCRIPTION
**Pull request by thomkle**
@hishamco I'm not sure if this is a functionality you want in your project, but the default [ASP.NET Core localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#culture-fallback-behavior) seems to have this kind of fallback: 
- _Welcome.fr-CA.resx_
- _Welcome.fr.resx_
- _Welcome.resx (if the NeutralResourcesLanguage is "fr-CA")_ (I've added a fix for this in the pull request)

I'm basically adding a "root" resource as well, using "root" as a cache name (since e.g. the root resource `Test.json` doesn't have a culture name). Also separated the whole _build->get string_ logic to make it easier to reuse when adding the "root" resource.

I also fixed some failing unit tests.

What do you think?

### CODE REVIEW

**Comment by hishamco** [comment]
> if the NeutralResourcesLanguage is "fr-CA"

I saw your earlier comment in the previous issue but I did not think about neutral resource language

I will open review your PR ASAP

**Comment by thomkle** [comment]
@hishamco Just to clarify, I did not add any support for or handle the `NeutralResourcesLanguage`-variable (not sure how that's used). I just added a netural "root" resource that all cultures will fall back to if they don't have a key in their culture specific resource files.

**Comment by hishamco** [comment]
>  I did not add any support for or handle the NeutralResourcesLanguage-variable (not sure how that's used).

I just open my laptop, and that's the question I wanna ask ;)

**Comment by hishamco** [comment]
> I just added support for a netural "root" resource that all cultures will fall back to if they don't have a key in their culture specific resource files.

Frankly I'm not sure because I didn't try `NeutralResourcesLanguage` before, AFAIK the fallback process for `es-MX` & `en-US` will be as the following:

es-MX -> es -> ""
en-US -> en -> ""

Where "" is a Neutral Culture

The question is if the app supports more than one culture, and the specified key is not exist, all the values will be similar for each cultures which is wrong

Let me try if we can use a `NeutralResourcesLanguage` somehow ...

**Comment by hishamco** [comment]
FYI we can use `NeutralResourcesLanguageAttribute` http://hishambinateya.com/neutralresourceslanguageattribute-doesn't-respect-localization-in-asp.net-core

Please let me know if you wish to continue on this or I may push some commits to your PR

**Comment by thomkle** [comment]
Of course, you're welcomed to push commits to the PR, especially since you've worked with the attribute before. I agree, we should use the `NeutralResourcesLanguageAttribute` if possible and I think I know what you mean and that's ultimately what I want to achieve I believe. Say we set the `[assembly:NeutralResourcesLanguage("en-US")]`, then we don't add the en-US keys to `Test.en-US.json`, but to `Test.json` and all cultures will fall back to this file if the key isn't present in their culture specific resource file. Right? 

Another thought: What happens if we provide a `Test.en.json`, but the key isn't there. Since en is the parent of en-US, will this fall back to it's "child" since en-US is set as the neutral resource language? Or should the neutral resource language be `[assembly:NeutralResourcesLanguage("en")]` instead?

**Comment by hishamco** [comment]
If I'm not wrong the provided in `NeutralResourcesLanguage` should be able to access `Resource.json`, regarding the fallback it should respect `RequestLocalizationOptions.FallBackToSupportedUICultures`

**Comment by thomkle** [comment]
> The question is if the app supports more than one culture, and the specified key is not exist, all the values will be similar for each cultures which is wrong

Actually, isn't this a wanted functionality? Say we have a lot of translations for English, but only some for Spanish. If a user asks for Spanish, then he'll get the translation if it's available. If not, it will fall back to the neutral fall back language, English. Or did I misunderstand?

**Comment by thomkle** [comment]
> If I'm not wrong the provided in `NeutralResourcesLanguage` should be able to access `Resource.json`, regarding the fallback it should respect `RequestLocalizationOptions.FallBackToSupportedUICultures`

Didn't see your reply until now.
Ok, if we respect the fallback-option, that would make the scenario I suggested in the previous comment possible?

**Comment by hishamco** [comment]
Don't forgot now we are fallback all the time, so that's why I filed #27

**Comment by hishamco** [comment]
`NeutralResourcesLanguageAttribute` is related to `System.Resources` aka resx, so I decide to not support this attribute, instead the fallback will the current culture hierarchy if it's supported otherwise will use the default culture in the localization APIs, so in your above scenario the localizer will look into:

1- Welcome.fr-CA.resx
2- Welcome.fr.resx
3- Welcome.resx (if the  is "fr-CA" is default culture)

but in case of `es-MX` the localizer will look into:

1- Welcome.es-MX.resx
2- Welcome.es.resx

**Comment by hishamco** [comment]
@thomkle seems I'm unable to push commits into your pr, there 's a checkbox on the right of the page that allow the maintainer to add commits, so please check it or I will start a new PR instead

**Comment by hishamco** [comment]
I just created a PR #41 that resolve the issue, but this introduce a breaking change similar to what I wanna do in #27, so the decision will not be so fast this time ;) but absolutely will be in `3.0.0`

FYI there 're many features I wanna add, but I will check if all goes into a major release or we can release a minor release before

Thanks

**Comment by hishamco** [comment]
For now you can keep the reusable changes that you made and revert other changes, so I can do a final review an merge this

**Comment by thomkle** [comment]
> @thomkle seems I'm unable to push commits into your pr, there 's a checkbox on the right of the page that allow the maintainer to add commits, so please check it or I will start a new PR instead

Sorry, been away for a few days. But the checkbox is already checked!

**Comment by thomkle** [comment]
> I just created a PR #41 that resolve the issue, but this introduce a breaking change similar to what I wanna do in #27, so the decision will not be so fast this time ;) but absolutely will be in `3.0.0`
> 
> FYI there 're many features I wanna add, but I will check if all goes into a major release or we can release a minor release before
> 
> Thanks

I see, but will I be able to have the functionality that I explained earlier with that change? E.g. if I have a Test.en-US.json, Test.es-ES.json and Test.json where the requested key only exists in Test.json. Will both languages be able to fall back to Test.json? Or only the language that is the neutral language?

That's kind of my issue you see, if I request a key, if the key doesn't exist for es-ES (or any language file that doesn't have the key) it will fall back and resolve the key that exists in the root resource. Otherwise the languages without that key (and is not the default language) will just show a key instead, right?

**Comment by hishamco** [comment]
The workaround for this is to subclass `JsonStringLocalizer` until we ship it

**Comment by thomkle** [comment]
I see, so the plan is to support the mentioned functionality and not just fall back to Test.json for the neutral language, but for all languages?

No problem at all, did you want any of the changes in this PR? Or did you reimplement what you needed in #41 ?

**Comment by hishamco** [comment]
> No problem at all, did you want any of the changes in this PR?

If you did some refactoring that doesn't introduce any breaking changes I can accept it, the PR #41 will be an implementation for the culture fallback

**Comment by hishamco** [comment]
We can use this fallback and write some docs, so people will know how the fallback will be

**Comment by thomkle** [comment]
> > No problem at all, did you want any of the changes in this PR?
> 
> If you did some refactoring that doesn't introduce any breaking changes I can accept it, the PR #41 will be an implementation for the culture fallback

I don't think there were that many changes except the fallback stuff. Just fixing and adding some tests and moving functionality.

**Comment by thomkle** [comment]
> We can use this fallback and write some docs, so people will know how the fallback will be

We could actually follow the mentioned fallback:
1- Welcome.fr-CA.resx
2- Welcome.fr.resx
3- Welcome.resx (if the is "fr-CA" is default culture)

And then add an option to the `JsonLocalizationOptions.cs` that would also support fallback for non-default cultures? That way, the users of the library controls the functionality. What do you think?

**Comment by hishamco** [comment]
If you look closely to my PR that's what I did using the proper `RequestLocalizationOptions`

**Comment by thomkle** [comment]
I think we're misunderstanding each other. With your PR, it will only fall back to Test.json if the current culture is the default culture, right? I'm talking about having an option to also support fallback for non-default cultures. Does that make sense?

An example of a situation for the current PR: Say the default culture is es-ES, but the current culture is en-US. The requested key has no entry in the Test.en-US.json file, but in the Test.json file. It never gets that value because the default culture is not equal to the current culture. 

I'm talking about an option that makes it possible for this situation to get that value from the Test.json (non-default cultures falling back to the root resource file). E.g. `FallBackToRootResource` where by default it's false, but makes it possible to enable by the user of the library.

**Comment by hishamco** [comment]
> I think we're misunderstanding each other. With your PR, it will only fall back to Test.json if the current culture is the default culture, right?

Exactly

> I'm talking about having an option to also support fallback for non-default cultures. Does that make sense?

I'm not sure if it's make sense, introducing `FallBackToRootResource` may be confusing with `FallBackToSupportedCultures`, Am I right, or convince me ;)

**Comment by hishamco** [comment]
May be we can let the localizer do the following fallback mechanism:

1- Welcome.`{culture}`.resx
2- Welcome.`{parent-culture}`.resx
3- Welcome.resx

for every culture, but I'm still thinking about any implications

**Comment by thomkle** [comment]
> > I think we're misunderstanding each other. With your PR, it will only fall back to Test.json if the current culture is the default culture, right?
> 
> Exactly
> 
> > I'm talking about having an option to also support fallback for non-default cultures. Does that make sense?
> 
> I'm not sure if it's make sense, introducing `FallBackToRootResource` may be confusing with `FallBackToSupportedCultures`, Am I right, or convince me ;)

You're right. The name doesn't matter that much for me. The main idea is to expose the option to the user of the library through the `JsonLocalizationOptions`.

**Comment by thomkle** [comment]
> May be we can let the localizer do the following fallback mechanism:
> 
> 1- Welcome.`{culture}`.resx
> 2- Welcome.`{parent-culture}`.resx
> 3- Welcome.resx
> 
> for every culture, but I'm still thinking about any implications

I don't think the implications would be large if the option is "optional" by being false by default. Then the fall back would be by default:
1- Welcome.fr-CA.resx
2- Welcome.fr.resx
3- Welcome.resx (if the is "fr-CA" is default culture)

but if we set the option to true, it would be 

1- Welcome.{culture}.resx
2- Welcome.{parent-culture}.resx
3- Welcome.resx

for every culture.

What do you think? I think it's a very normal and useful behavior. Otherwise, if you don't have a translation of a language, you won't get the "back-up" translation from the default culture.

**Comment by hishamco** [comment]
> I don't think the implications would be large if the option is "optional" by being false by default.

I'm thinking about breaking changes ;), coz the this is not suited in `JsonLocalizationOptions`, may be `RequestLocalizationOptions` is better choice, I can made a PR for it, but if you interest let me know, so we discuss what should be the changes to avoid introducing any breaking changes if it's possible

Thanks

**Comment by thomkle** [comment]
> > I don't think the implications would be large if the option is "optional" by being false by default.
> 
> I'm thinking about breaking changes ;), coz the this is not suited in `JsonLocalizationOptions`, may be `RequestLocalizationOptions` is better choice, I can made a PR for it, but if you interest let me know, so we discuss what should be the changes to avoid introducing any breaking changes if it's possible
> 
> Thanks

Ok, I see, so then we would have to extend the `RequestLocalizationOptions` and add it there?

It's already a breaking change making the functionality be like this:
1- Welcome.fr-CA.resx
2- Welcome.fr.resx
3- Welcome.resx (if the is "fr-CA" is default culture)

right? Because in the current master there are no fall back to the root resource.

But going from that change to supporting:
1- Welcome.{culture}.resx
2- Welcome.{parent-culture}.resx
3- Welcome.resx

should be possible as a non-breaking change by adding the option to e.g. `RequestLocalizationOptions`.

I can try to demonstrate what I mean in a PR where I start from your changes in #41 tomorrow if you'd like?

**Comment by hishamco** [comment]
> Ok, I see, so then we would have to extend the RequestLocalizationOptions and add it there?

Exactly

> right? Because in the current master there are no fall back to the root resource.

No, what I mean is APIs breaking change, we will struggle to break anything in the `2.0.0` release as much as we can

> I can try to demonstrate what I mean in a PR where I start from your changes in #41 tomorrow if you'd like?

my PR introduces a breaking changes, that's why I didn't merge it ;)

**Comment by thomkle** [comment]
> > Ok, I see, so then we would have to extend the RequestLocalizationOptions and add it there?
> 
> Exactly
> 
> > right? Because in the current master there are no fall back to the root resource.
> 
> No, what I mean is APIs breaking change, we will struggle to break anything in the `2.0.0` release as much as we can
> 
> > I can try to demonstrate what I mean in a PR where I start from your changes in #41 tomorrow if you'd like?
> 
> my PR introduces a breaking changes, that's why I didn't merge it ;)

Ah, I see. What if we extended the `RequestLocalizationOptions` and added an enum option with 3 options.

1. `Default` (the functionality is the same as 2.0.0 (with no fall back to the root/default culture)
2. `FallBackToRootIfDefaultCulture` (the name can be anything)
3. `FallBackToRoot` (again, the name can be anything)

`FallBackToRootIfDefaultCulture` has the following fall back:
1- Welcome.fr-CA.resx
2- Welcome.fr.resx
3- Welcome.resx (if the "fr-CA" is default culture)

`FallBackToRoot` has the following fall back:
1- Welcome.{culture}.resx
2- Welcome.{parent-culture}.resx
3- Welcome.resx

And here's the non-breaking change: If the user of the library haven't done any changes, there will be no extended version of the `RequestLocalizationOptions` used, if that's the case we set the enum to `Default` (either in the factory or in the localizer). And then we implement the different scenarios. What do you think? This way the user getting the next version won't notice any difference, but will have the option to use the extended version of the `RequestLocalizationOptions` to set the new enum and change the fall back functionality.

**Comment by hishamco** [comment]
Please copy you last thread and file a new issue to make everything clear, I will close this while it's not make sense for now

Thanks

**Comment by thomkle** [comment]
I think it would be easier to understand what I mean if I just create a commit for it. Don't have to initiate a PR, I can link to the commit in my fork. Would that be ok?

**Comment by hishamco** [comment]
Does it mean you will update this PR?

**Comment by thomkle** [comment]
I can if that's easier. Let me know what you prefer.

**Comment by hishamco** [comment]
Sounds good

**Comment by hishamco** [comment]
`FallBackToRoot` it much simpler ;) please let me think about this before you spend time for things that may changed

I will try to reply ASAP

**Comment by thomkle** [comment]
Of course, let me know when you've come up with something or want input :)

**Comment by hishamco** [comment]
IMHO my PR is suitable fix to align with localization behavior, introducing ``FallBackToRootResource` in either way we let us change the constructor of `JsonStringLocalizer` or `JsonStringLocalizerFactory`. Am I right?

For that let us delay this until we decide the upcoming version will be `3.0.0` and there's no minor release, so now you can subclass our localizer to make things work for you at least

**Comment by thomkle** [comment]
Alright, sure thing

**Pull request closed without merging**
